name = "actor_squares"
version = "1.0.0"
description = "Actor-model Gleam project: find starts s in 1..N where sum_{i=0}^{k-1} (s+i)^2 is a perfect square."
licenses = ["MIT"]
target = "erlang"

[dependencies]
gleam_stdlib = "~> 0.30"
gleam_erlang = ">= 0.20.0"
gleam_otp = "~> 1.0"


[dev-dependencies]
gleeunit = "~> 1.0"
